builds:
  - ldflags:
      - -X main.version={{.Version}} -X main.commit={{.Commit}} -s -w
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarm:
      - 6
      - 7
release:
  prerelease: auto
  footer: |
    You can verify the signatures of the checksums.txt file using [cosign](https://github.com/sigstore/cosign).

    ```
    cosign verify-blob checksums.txt --signature=checksums.txt.sig  --key https://artifacts.fairwinds.com/cosign.pub
    ```
signs:
- cmd: cosign
  args: ["sign-blob", "--key=hashivault://cosign", "-output-signature=${signature}", "${artifact}"]
  artifacts: checksum
checksum:
  name_template: "checksums.txt"
dockers:
- image_templates:
  - "quay.io/fairwinds/reckoner:go-{{ .Tag }}"
  - "quay.io/fairwinds/reckoner:go-v{{ .Major }}"
  - "quay.io/fairwinds/reckoner:go-v{{ .Major }}.{{ .Minor }}"
  dockerfile: Dockerfile-go
